# Generated by Django 2.2.14 on 2020-11-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount_number', models.CharField(max_length=255)),
                ('bankaccount_totalvalue', models.IntegerField()),
                ('bankaccount_loan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_info_UserName', models.CharField(max_length=255)),
                ('client_info_Password', models.CharField(max_length=255)),
                ('client_info_Name', models.CharField(max_length=255)),
                ('client_info_Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='bankinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankinfo_credit', models.IntegerField()),
                ('bankinfo_credit_date', models.DateField(auto_now_add=True)),
                ('bankinfo_debit', models.IntegerField()),
                ('bankinfo_debit_date', models.DateField(auto_now_add=True)),
                ('bankinfo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bankaccount_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.client_info'),
        ),
    ]
