# Generated by Django 3.1.3 on 2020-12-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_spideridentifyrequest_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='spideruserlog',
            name='log_ticket',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
